### ISSUE TITLE
Add to homebrew when the repo is popular enough

### ISSUE THREAD

**Issue by RulerOf** [tmccombs/hcl2json#10]
Hi.

So I wrote [a homebrew formula](https://github.com/RulerOf/homebrew-core/commit/ff9109f212601f57be60aedb7dfdf91c6347b8ba) for this tool after discovering that everything else that does CLI-based hcl->json conversion is either old or bad (or both).

Homebrew, however, is a little obnoxious, and doesn't think this tool is notable enough:
```
18:25 $ brew audit --new-formula hcl2json
hcl2json:
  * GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
Error: 1 problem in 1 formula detected
```

So... I'm basically just dropping this note here. You can poke me when this threshold is reached, and/or submit it yourself.

In the meantime, anyone who is interested can install it manually using:
```shell
brew install https://raw.githubusercontent.com/RulerOf/homebrew-core/ff9109f212601f57be60aedb7dfdf91c6347b8ba/Formula/hcl2json.rb
```

**Comment by mafrosis** [comment]
Just stumbled upon this issue.. and hey! You have 85 stars ⭐

**Comment by RulerOf** [comment]
@mafrosis oh hey thanks for the notification! I don't remember this process at all at this point, and probably won't get a chance to take care of this for at least a few weeks. If you'd like to submit ahead of me, by all means do so, otherwise I'll sticky this notification and take care of it as soon as I get a chance

**Comment by gpetrov** [comment]
Maybe add a `scoop` compatibility as well so it can be installed easy on Windows

**Comment by RulerOf** [comment]
@tmccombs `hcl2json` is now available in Homebrew :)
