### ISSUE TITLE
Add usage instructions

### ISSUE THREAD

**Issue by tdmalone** [tmccombs/hcl2json#11]
Thank you firstly for putting this together!

I'm not a Go programmer so it took me a little while to figure out how to use this.

My first guess did not yield fruit:
```
$ go get github.com/tmccombs/hcl2json
package github.com/hashicorp/hcl/v2: cannot find package "github.com/hashicorp/hcl/v2" in any of:
        /usr/local/go/src/github.com/hashicorp/hcl/v2 (from $GOROOT)
        /Users/tim/go/src/github.com/hashicorp/hcl/v2 (from $GOPATH)
package github.com/hashicorp/hcl/v2/hclsyntax: cannot find package "github.com/hashicorp/hcl/v2/hclsyntax" in any of:
        /usr/local/go/src/github.com/hashicorp/hcl/v2/hclsyntax (from $GOROOT)
        /Users/tim/go/src/github.com/hashicorp/hcl/v2/hclsyntax (from $GOPATH)
```
(might be similar to #8)

But I eventually settled on:
```
git clone git@github.com:tmccombs/hcl2json.git
cd hcl2json
docker build -t hcl2json .
docker run -i hcl2json < /path/to/*.tf
```

Just wondering if you could add your recommend mode of usage to the README to help others coming across this? (I would PR, but I'm sure you will know what I did wrong with `go get`!)

**Comment by tmccombs** [comment]
> I would PR, but I'm sure you will know what I did wrong with go get!

unfortunately, I'm not really sure the correct way to install using `go get`. I think you are right that it is the same as #8. It has something to do with go modules, and the way hclv2 was published. 

I'm not much of a go expert myself, and I'm not quite sure how to fix it, or if it is fixable. It seems like `go get` is just refusing to use go modules.
