### ISSUE TITLE
Expose HCL to JSON as package

### ISSUE THREAD

**Issue by jpreese** [tmccombs/hcl2json#15]
We would like to use this functionality in another Go app, specifically taking an HCL file and getting its JSON representation. However, all of the methods are private.

Any objections to _packaging_ 🥁 up this logic into a package? Happy to do a PR!

**Comment by tmccombs** [comment]
I have no objection to that. Especially if you send a PR :)

**Comment by jpreese** [comment]
Resolves https://github.com/tmccombs/hcl2json/issues/15

- Bump the expected Go version in `go.mod` to `1.14` to match the CircleCI config
- Expose two functions that are capable of converting HCL
  - `HCLBytes` to convert an HCL file that has already been read and the bytes are available.
  - `HCLFile` to convert a typed HCL file
