### ISSUE TITLE
Publish new Docker image for 0.3.4

### ISSUE THREAD

**Issue by raharrison** [tmccombs/hcl2json#48]
Is it possible for a new image to be published to Docker Hub for the latest release? Last published image is a couple years old now.

**Comment by tmccombs** [comment]
0.3.5 is available at https://hub.docker.com/layers/tmccombs/hcl2json/0.3.5/images/sha256-1774b163bba488d5239c698dfa33d156faf05b947b93d9ea8b3aeb538e208ff3?context=repo
