### ISSUE TITLE
Use of the archived and experimental hcl2 library

### ISSUE THREAD

**Issue by menendezjaume** [tmccombs/hcl2json#5]
It seems that we are pulling a library that was experimental and is no longer supported by the vendor see [Hashicorp's HCL Readme](https://github.com/hashicorp/hcl2/#experimental-hcl2).

According to their docs, they advise everyone to move to the newest versions, hosted in the hcl2 branch of the [HCL Project](https://github.com/hashicorp/hcl).

See for more information: [Version Selection Guide](https://github.com/hashicorp/hcl/wiki/Version-Selection).

I'll open a PR to upgrade to this version of the HCLv2 library.

**Comment by tmccombs** [comment]
> I'll open a PR to upgrade to this version of the HCLv2 library.

That would be awesome. Thank you.

**Comment by tmccombs** [comment]
This was done in 5c1402dc2b410e362afee45a3cf15dcb08bc1f2c
