### ISSUE TITLE
--slurp option

### ISSUE THREAD

**Issue by paololazzari** [tmccombs/hcl2json#55]
If I have two JSON files:

```json
{
    "k":{
        "a":"foo"
    }
}
```

```json
{
    "k":{
        "b":"bar"
    }
}
```

I can do:

```bash
$ jq -s '.' *.json
[
  {
    "k": {
      "a": "foo"
    }
  },
  {
    "k": {
      "b": "bar"
    }
  }
]
```

it would be nice to have the same functionality for hcl2json

**Comment by tmccombs** [comment]
I made a PR that I think addresses this.

**Comment by paololazzari** [comment]
Hi @tmccombs ,

Thank you for the quick turnaround. I tried the fix and I can confirm it works.
