### ISSUE TITLE
Fails to parse tags with periods in name

### ISSUE THREAD

**Issue by robeden** [tmccombs/hcl2json#7]
This configuration works in terraform and some other HCL->Json converters but results in an error for hcl2json:

```
resource "aws_s3_bucket" "design_bucket" {
  # non-relevant config

  tags {
    something.more.even_more = "True"
  }
}
```

This is an example of the error output:
> Failed to convert file: main.tf:30,5-20: Argument or block definition required; An argument or block definition is required here. To set an argument, use the equals sign "=" to introduce the argument value.

**Comment by tmccombs** [comment]
hmm, this might be a limitation of the hcl library. 

I've determined that the error actually occurs in a call to `hclsyntax.ParseConfig`. So the hcl2 library isn't even able to parse the hcl syntax. Interestingly, if you have 

```
tags = {
    something.more.even_more = "True"
}
```

it seems to parse fine.

**Comment by robeden** [comment]
Interesting. It works in terraform 0.11.x, but I haven't checked in 0.12. Perhaps they "broke" (or fixed?) it there.

**Comment by tmccombs** [comment]
This hcl2json tool is specifically for hcl version 2. terraform 0.11.x uses hcl 1, but terraform 0.12 uses hcl 2. hcl 2 is not backwards compatible with hcl 1, it could very well be that this is one of the things that changed, although I'm not familiar with a specific breaking change that is responsible for this.

**Comment by tmccombs** [comment]
I'm closing this as I don't think this is an issue with hcl2json itself. If you think it should remain open, let me know.
