### ISSUE TITLE
GO version critical CVEs

### ISSUE THREAD

**Issue by corbin-lounsbury** [tmccombs/hcl2json#88]
Based on a scan we did on the image, it looks like the GO version used in the binaries is vulnerable.

https://github.com/advisories/GHSA-rxv8-v965-v333 and https://github.com/advisories/GHSA-679v-hh23-h5jh
Path: /0.5.0/bin/0.6.0/hcl2json_linux_arm64

Recommended course of action: Upgrade GO to 1.21.2 or higher

**Comment by tmccombs** [comment]
Released new version: https://github.com/tmccombs/hcl2json/releases/tag/v0.6.1
